/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { createUser } from "../funcs/createUser.js";
import { getUser } from "../funcs/getUser.js";
import { listUsers } from "../funcs/listUsers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ExampleAPI extends ClientSDK {
  /**
   * List all users
   *
   * @remarks
   * Returns a list of users
   */
  async listUsers(
    options?: RequestOptions,
  ): Promise<Array<models.User>> {
    return unwrapAsync(listUsers(
      this,
      options,
    ));
  }

  /**
   * Create a user
   *
   * @remarks
   * Creates a new user
   */
  async createUser(
    request: models.CreateUserRequest,
    options?: RequestOptions,
  ): Promise<models.User> {
    return unwrapAsync(createUser(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a user
   *
   * @remarks
   * Returns a single user by ID
   */
  async getUser(
    id: string,
    options?: RequestOptions,
  ): Promise<models.User> {
    return unwrapAsync(getUser(
      this,
      id,
      options,
    ));
  }
}
