/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @speakeasy-sdks/example-api SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx listUsers.example.ts
 */

import { ExampleAPI } from "@speakeasy-sdks/example-api";

const exampleAPI = new ExampleAPI();

async function main() {
  const result = await exampleAPI.listUsers();

  console.log(result);
}

main().catch(console.error);
