workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    example-api:
        inputs:
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/example-api@$TAG
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/example-api
targets:
    typescript:
        target: typescript
        source: example-api
        output: .
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/example-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
