/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateUserRequest = {
  /**
   * User's email address
   */
  email: string;
  /**
   * User's full name
   */
  name: string;
};

/** @internal */
export type CreateUserRequest$Outbound = {
  email: string;
  name: string;
};

/** @internal */
export const CreateUserRequest$outboundSchema: z.ZodMiniType<
  CreateUserRequest$Outbound,
  CreateUserRequest
> = z.object({
  email: z.string(),
  name: z.string(),
});

export function createUserRequestToJSON(
  createUserRequest: CreateUserRequest,
): string {
  return JSON.stringify(
    CreateUserRequest$outboundSchema.parse(createUserRequest),
  );
}
