/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type User = {
  /**
   * Unique identifier for the user
   */
  id: string;
  /**
   * User's email address
   */
  email: string;
  /**
   * User's full name
   */
  name: string;
  /**
   * When the user was created
   */
  createdAt?: Date | undefined;
};

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.object({
  id: types.string(),
  email: types.string(),
  name: types.string(),
  createdAt: types.optional(types.date()),
});

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
